export const SHIPMENT_TYPE_OPTIONS: { value: string; label: string }[] = [
  { value: "general", label: "General" },
  { value: "pallet", label: "Pallet" },
  { value: "container", label: "Container" },
  { value: "loose", label: "Loose" },
  { value: "pet", label: "Pet" },
  { value: "documents", label: "Documents" },
  { value: "electronics", label: "Electronics" },
  { value: "furniture", label: "Furniture" },
  { value: "clothing", label: "Clothing" },
  { value: "personal_effects", label: "Personal effects" },
  { value: "food_perishables", label: "Food / Perishables" },
  { value: "art_antiques", label: "Art / Antiques" },
  { value: "vehicles_parts", label: "Vehicles / Parts" },
  { value: "machinery", label: "Machinery" },
  { value: "hazardous", label: "Hazardous materials" },
  { value: "medical", label: "Medical / Pharma" },
  { value: "retail_goods", label: "Retail goods" },
  { value: "raw_materials", label: "Raw materials" },
  { value: "textiles", label: "Textiles" },
  { value: "other", label: "Other" },
];
